/**
 * The app's own JWT signing key (RLS-01).
 *
 * WHY WE SIGN OUR OWN, rather than using a Supabase shared secret: this project
 * migrated to asymmetric JWT signing. Its ES256 key is `in_use` and Supabase
 * exposes only the public half; the old HS256 shared secret is
 * `previously_used`, i.e. retired and kept alive only so already-issued tokens
 * (the legacy anon / service_role keys) still validate. There is no secret to
 * borrow, and signing with a retired key would fail silently the moment the
 * grace window closed - `public.user_id()` would return NULL and every policy
 * would match zero rows without erroring.
 *
 * So Taruu becomes its own token issuer. We hold an EC P-256 private key,
 * publish the public half as a JWKS, and register that URL with Supabase as a
 * third-party auth issuer. Supabase fetches the JWKS, caches it, and re-checks
 * periodically. Nothing secret ever leaves this server.
 *
 * The keypair is generated by scripts/setup-supabase-third-party-auth.sh.
 */

import { importJWK, exportJWK, type JWK, type KeyLike } from 'jose';

/** ES256 = ECDSA on P-256. Supabase requires an asymmetric algorithm. */
export const SIGNING_ALG = 'ES256';

interface PrivateJwk extends JWK {
  kid?: string;
  d?: string;
}

let cached: { key: KeyLike | Uint8Array; kid: string } | null = null;
let cachedPublicJwks: { keys: JWK[] } | null = null;

function readPrivateJwk(): PrivateJwk {
  const raw = process.env.SUPABASE_TP_PRIVATE_JWK;
  if (!raw) {
    throw new Error('Missing SUPABASE_TP_PRIVATE_JWK environment variable');
  }

  let parsed: PrivateJwk;
  try {
    parsed = JSON.parse(raw) as PrivateJwk;
  } catch {
    throw new Error('SUPABASE_TP_PRIVATE_JWK is not valid JSON (expected a private JWK)');
  }

  if (!parsed.d) {
    // A JWK without `d` is the PUBLIC half. Signing with it is impossible, and
    // the mistake is easy to make when copying between the two.
    throw new Error('SUPABASE_TP_PRIVATE_JWK has no "d" — that is a public key, not a private one');
  }
  if (!parsed.kid) {
    // Supabase requires a kid header to select the verification key.
    throw new Error('SUPABASE_TP_PRIVATE_JWK has no "kid" — Supabase needs it to pick the key');
  }

  return parsed;
}

/** The private signing key and its kid. Memoized: importJWK is not free. */
export async function getSigningKey(): Promise<{ key: KeyLike | Uint8Array; kid: string }> {
  if (cached) return cached;

  const jwk = readPrivateJwk();
  const key = await importJWK(jwk, SIGNING_ALG);
  cached = { key, kid: jwk.kid as string };
  return cached;
}

/**
 * The PUBLIC half, in JWKS form, for `/.well-known/jwks.json`.
 *
 * Derived from the private key by dropping `d` rather than stored separately,
 * so the published key and the signing key cannot drift apart.
 */
export async function getPublicJwks(): Promise<{ keys: JWK[] }> {
  if (cachedPublicJwks) return cachedPublicJwks;

  const jwk = readPrivateJwk();
  const key = await importJWK(jwk, SIGNING_ALG);
  const publicJwk = await exportJWK(key);

  // exportJWK on a private key still carries `d`; strip it explicitly rather
  // than trusting the shape. Publishing `d` would hand out the signing key.
  delete (publicJwk as PrivateJwk).d;

  cachedPublicJwks = {
    keys: [
      {
        ...publicJwk,
        kid: jwk.kid,
        alg: SIGNING_ALG,
        use: 'sig',
        key_ops: ['verify'],
      },
    ],
  };
  return cachedPublicJwks;
}

/** Test seam. Production never calls this. */
export function resetSigningKeyCache(): void {
  cached = null;
  cachedPublicJwks = null;
}
